const test=require('node:test');const assert=require('node:assert/strict');const request=require('supertest');const {db:makeDb}=require('./helpers');const audit=require('../../src/services/audit');const {resolveWorkspaceAccess}=require('../../src/middleware/workspace-guard');const {consume,rateLimit}=require('../../src/middleware/rate-limit');const {createApp}=require('../../src/server');const sweeper=require('../../src/services/demo-sweeper');
function setup(){const x=makeDb();test.after(()=>x.db.close());return x.db;}
test('migrations are idempotent and seed 50 techniques',()=>{const db=setup();assert.equal(db.prepare('select count(*) n from techniques').get().n,50);const {runMigrations}=require('../../src/db');runMigrations(db);assert.equal(db.prepare('select count(*) n from techniques').get().n,50);});
test('workspace guard denies non-member and allows matching demo session',()=>{const db=setup();db.prepare("insert into workspaces(id,name) values('w1','one'),('w2','two')").run();db.prepare("insert into users(id,email,name,password_hash) values('u','u@x','U','x')").run();assert.deepEqual(resolveWorkspaceAccess(db,{user:{id:'u'},session:{}},'w2').ok,false);assert.deepEqual(resolveWorkspaceAccess(db,{session:{demoWorkspaceId:'w1'}},'w1'),{ok:true,role:'owner',isDemo:true});});
test('rate limiter fails closed and never next on storage error',()=>{const db=setup();const mw=rateLimit({bucket:'x',max:1,windowMs:1000});let status,body,called=false;const req={ip:'1',app:{locals:{db:{prepare(){throw Error('storage')}}}}};const res={status(n){status=n;return this},json(x){body=x;return this},set(){return this}};mw(req,res,()=>{called=true});assert.equal(status,503);assert.equal(called,false);assert.equal(body.error,'Rate limiter unavailable');});
test('audit chain verifies and catches hash and prev tampering independently',()=>{const db=setup();db.prepare("insert into workspaces(id,name) values('a','A'),('b','B')").run();for(let i=0;i<3;i++)audit.append(db,{workspaceId:'a',action:'x',targetType:'t',targetId:String(i),payload:{i}});audit.append(db,{workspaceId:'b',action:'x',targetType:'t',targetId:'b',payload:{}});assert.deepEqual(audit.verify(db,'a'),{valid:true,checked:3});const mid=db.prepare("select id from audit_log where workspace_id='a' order by rowid limit 1 offset 1").get(); // test-only raw SQL integrity fixture: corrupt the middle hash.
db.exec(`UPDATE audit_log SET hash='bad' WHERE id='${mid.id}'`);assert.equal(audit.verify(db,'a').brokenAtId,mid.id);assert.equal(audit.verify(db,'b').valid,true);});
test('health, session response, cookie and stubs',async()=>{const db=setup();const app=createApp(db,{startSweeper:false});let r=await request(app).get('/api/auth/session');assert.equal(r.status,200);assert.deepEqual(r.body,{user:null,workspaces:[]});r=await request(app).get('/api/incidents');assert.equal(r.status,404);r=await request(app).get('/api/techniques');assert.equal(r.status,404);r=await request(app).get('/api/incidents/x/evidence');assert.equal(r.status,404);r=await request(app).get('/api/incidents/x/export.pdf');assert.equal(r.status,404);r=await request(app).post('/api/demo');assert.equal(r.status,404);r=await request(app).get('/health');assert.equal(r.status,200);assert.equal(r.body.db,'ok');});
test('registration limiter sixth request is 429',async()=>{const db=setup();const app=createApp(db,{startSweeper:false});for(let i=0;i<5;i++){const r=await request(app).post('/api/auth/register').send({email:`u${i}@x.test`,name:'User',password:'long-password'});assert.equal(r.status,201);}const sixth=await request(app).post('/api/auth/register').send({email:'u6@x.test',name:'User',password:'long-password'});assert.equal(sixth.status,429);});
test('demo sweeper start schedules and no-op does not change db',()=>{const db=setup();const before=db.prepare('select count(*) n from workspaces').get().n;const timer=sweeper.start(db,{intervalMs:60_000});assert.ok(timer);sweeper.sweep(db);assert.equal(db.prepare('select count(*) n from workspaces').get().n,before);clearInterval(timer);});
test('session regeneration changes cookie and removes demo grant on login',async()=>{const db=setup();const app=createApp(db,{startSweeper:false});const agent=request.agent(app);let r=await agent.get('/api/auth/session');assert.equal(r.status,200);const first=r.headers['set-cookie'];r=await agent.post('/api/auth/register').send({email:'regen@example.test',name:'Regen',password:'long-password'});assert.equal(r.status,201);const registered=r.headers['set-cookie'];assert.ok(registered);assert.match(registered[0],/SameSite=Lax/);assert.notEqual(first?.[0],registered?.[0]);await agent.post('/api/auth/logout');r=await agent.post('/api/auth/login').send({email:'regen@example.test',password:'long-password'});assert.equal(r.status,200);assert.ok(r.headers['set-cookie']);});
test('health fails closed on SELECT error',async()=>{const db=setup();const app=createApp(db,{startSweeper:false});const original=db.prepare.bind(db);db.prepare=(sql)=>{if(sql==='SELECT 1')throw Error('db down');return original(sql)};const r=await request(app).get('/health');assert.equal(r.status,503);assert.deepEqual(r.body,{status:'error',db:'error'});});
test('hub broadcasts, heartbeats, and disconnect cleanup',async()=>{const hub=require('../../src/sse/hub');const events=[];const listeners={};const res={set(){},flushHeaders(){},write(x){events.push(x)},on(e,fn){listeners[e]=fn}};hub.subscribe('i',res,{heartbeatMs:10});assert.equal(hub.subscriberCount('i'),1);hub.broadcast('i','entry.created',{id:'e'});await new Promise(r=>setTimeout(r,25));assert.ok(events.some(x=>x.includes('event: entry.created')));assert.ok(events.some(x=>x.includes(': heartbeat')));listeners.close();assert.equal(hub.subscriberCount('i'),0);});

test('registration limiter storage failure returns 503',async()=>{const db=setup();const original=db.prepare.bind(db);db.prepare=(sql)=>{if(String(sql).includes('rate_limits'))throw Error('rate limit unavailable');return original(sql)};const app=createApp(db,{startSweeper:false});const r=await request(app).post('/api/auth/register').send({email:'fail@example.test',name:'Fail',password:'long-password'});assert.equal(r.status,503);});
