INSERT OR IGNORE INTO techniques (id, name, tactic, url) VALUES ('T1595', 'Active Scanning', 'Reconnaissance', 'https://attack.mitre.org/techniques/T1595/');
INSERT OR IGNORE INTO techniques (id, name, tactic, url) VALUES ('T1589', 'Gather Victim Identity Information', 'Reconnaissance', 'https://attack.mitre.org/techniques/T1589/');
INSERT OR IGNORE INTO techniques (id, name, tactic, url) VALUES ('T1598', 'Phishing for Information', 'Reconnaissance', 'https://attack.mitre.org/techniques/T1598/');
INSERT OR IGNORE INTO techniques (id, name, tactic, url) VALUES ('T1583', 'Acquire Infrastructure', 'Resource Development', 'https://attack.mitre.org/techniques/T1583/');
INSERT OR IGNORE INTO techniques (id, name, tactic, url) VALUES ('T1586', 'Compromise Accounts', 'Resource Development', 'https://attack.mitre.org/techniques/T1586/');
INSERT OR IGNORE INTO techniques (id, name, tactic, url) VALUES ('T1587', 'Develop Capabilities', 'Resource Development', 'https://attack.mitre.org/techniques/T1587/');
INSERT OR IGNORE INTO techniques (id, name, tactic, url) VALUES ('T1566', 'Phishing', 'Initial Access', 'https://attack.mitre.org/techniques/T1566/');
INSERT OR IGNORE INTO techniques (id, name, tactic, url) VALUES ('T1566.001', 'Spearphishing Attachment', 'Initial Access', 'https://attack.mitre.org/techniques/T1566/001/');
INSERT OR IGNORE INTO techniques (id, name, tactic, url) VALUES ('T1566.002', 'Spearphishing Link', 'Initial Access', 'https://attack.mitre.org/techniques/T1566/002/');
INSERT OR IGNORE INTO techniques (id, name, tactic, url) VALUES ('T1190', 'Exploit Public-Facing Application', 'Initial Access', 'https://attack.mitre.org/techniques/T1190/');
INSERT OR IGNORE INTO techniques (id, name, tactic, url) VALUES ('T1078', 'Valid Accounts', 'Initial Access', 'https://attack.mitre.org/techniques/T1078/');
INSERT OR IGNORE INTO techniques (id, name, tactic, url) VALUES ('T1059', 'Command and Scripting Interpreter', 'Execution', 'https://attack.mitre.org/techniques/T1059/');
INSERT OR IGNORE INTO techniques (id, name, tactic, url) VALUES ('T1059.001', 'PowerShell', 'Execution', 'https://attack.mitre.org/techniques/T1059/001/');
INSERT OR IGNORE INTO techniques (id, name, tactic, url) VALUES ('T1204', 'User Execution', 'Execution', 'https://attack.mitre.org/techniques/T1204/');
INSERT OR IGNORE INTO techniques (id, name, tactic, url) VALUES ('T1204.002', 'Malicious File', 'Execution', 'https://attack.mitre.org/techniques/T1204/002/');
INSERT OR IGNORE INTO techniques (id, name, tactic, url) VALUES ('T1053', 'Scheduled Task/Job', 'Persistence', 'https://attack.mitre.org/techniques/T1053/');
INSERT OR IGNORE INTO techniques (id, name, tactic, url) VALUES ('T1053.005', 'Scheduled Task', 'Persistence', 'https://attack.mitre.org/techniques/T1053/005/');
INSERT OR IGNORE INTO techniques (id, name, tactic, url) VALUES ('T1547', 'Boot or Logon Autostart Execution', 'Persistence', 'https://attack.mitre.org/techniques/T1547/');
INSERT OR IGNORE INTO techniques (id, name, tactic, url) VALUES ('T1136', 'Create Account', 'Persistence', 'https://attack.mitre.org/techniques/T1136/');
INSERT OR IGNORE INTO techniques (id, name, tactic, url) VALUES ('T1078.004', 'Valid Accounts: Cloud Accounts', 'Privilege Escalation', 'https://attack.mitre.org/techniques/T1078/004/');
INSERT OR IGNORE INTO techniques (id, name, tactic, url) VALUES ('T1055', 'Process Injection', 'Privilege Escalation', 'https://attack.mitre.org/techniques/T1055/');
INSERT OR IGNORE INTO techniques (id, name, tactic, url) VALUES ('T1068', 'Exploitation for Privilege Escalation', 'Privilege Escalation', 'https://attack.mitre.org/techniques/T1068/');
INSERT OR IGNORE INTO techniques (id, name, tactic, url) VALUES ('T1027', 'Obfuscated Files or Information', 'Defense Evasion', 'https://attack.mitre.org/techniques/T1027/');
INSERT OR IGNORE INTO techniques (id, name, tactic, url) VALUES ('T1070', 'Indicator Removal', 'Defense Evasion', 'https://attack.mitre.org/techniques/T1070/');
INSERT OR IGNORE INTO techniques (id, name, tactic, url) VALUES ('T1070.004', 'File Deletion', 'Defense Evasion', 'https://attack.mitre.org/techniques/T1070/004/');
INSERT OR IGNORE INTO techniques (id, name, tactic, url) VALUES ('T1562', 'Impair Defenses', 'Defense Evasion', 'https://attack.mitre.org/techniques/T1562/');
INSERT OR IGNORE INTO techniques (id, name, tactic, url) VALUES ('T1003', 'OS Credential Dumping', 'Credential Access', 'https://attack.mitre.org/techniques/T1003/');
INSERT OR IGNORE INTO techniques (id, name, tactic, url) VALUES ('T1003.001', 'LSASS Memory', 'Credential Access', 'https://attack.mitre.org/techniques/T1003/001/');
INSERT OR IGNORE INTO techniques (id, name, tactic, url) VALUES ('T1110', 'Brute Force', 'Credential Access', 'https://attack.mitre.org/techniques/T1110/');
INSERT OR IGNORE INTO techniques (id, name, tactic, url) VALUES ('T1552', 'Unsecured Credentials', 'Credential Access', 'https://attack.mitre.org/techniques/T1552/');
INSERT OR IGNORE INTO techniques (id, name, tactic, url) VALUES ('T1082', 'System Information Discovery', 'Discovery', 'https://attack.mitre.org/techniques/T1082/');
INSERT OR IGNORE INTO techniques (id, name, tactic, url) VALUES ('T1087', 'Account Discovery', 'Discovery', 'https://attack.mitre.org/techniques/T1087/');
INSERT OR IGNORE INTO techniques (id, name, tactic, url) VALUES ('T1018', 'Remote System Discovery', 'Discovery', 'https://attack.mitre.org/techniques/T1018/');
INSERT OR IGNORE INTO techniques (id, name, tactic, url) VALUES ('T1021', 'Remote Services', 'Lateral Movement', 'https://attack.mitre.org/techniques/T1021/');
INSERT OR IGNORE INTO techniques (id, name, tactic, url) VALUES ('T1021.001', 'Remote Desktop Protocol', 'Lateral Movement', 'https://attack.mitre.org/techniques/T1021/001/');
INSERT OR IGNORE INTO techniques (id, name, tactic, url) VALUES ('T1021.002', 'SMB/Windows Admin Shares', 'Lateral Movement', 'https://attack.mitre.org/techniques/T1021/002/');
INSERT OR IGNORE INTO techniques (id, name, tactic, url) VALUES ('T1550', 'Use Alternate Authentication Material', 'Lateral Movement', 'https://attack.mitre.org/techniques/T1550/');
INSERT OR IGNORE INTO techniques (id, name, tactic, url) VALUES ('T1560', 'Archive Collected Data', 'Collection', 'https://attack.mitre.org/techniques/T1560/');
INSERT OR IGNORE INTO techniques (id, name, tactic, url) VALUES ('T1074', 'Data Staged', 'Collection', 'https://attack.mitre.org/techniques/T1074/');
INSERT OR IGNORE INTO techniques (id, name, tactic, url) VALUES ('T1074.001', 'Local Data Staging', 'Collection', 'https://attack.mitre.org/techniques/T1074/001/');
INSERT OR IGNORE INTO techniques (id, name, tactic, url) VALUES ('T1071', 'Application Layer Protocol', 'Command and Control', 'https://attack.mitre.org/techniques/T1071/');
INSERT OR IGNORE INTO techniques (id, name, tactic, url) VALUES ('T1071.001', 'Web Protocols', 'Command and Control', 'https://attack.mitre.org/techniques/T1071/001/');
INSERT OR IGNORE INTO techniques (id, name, tactic, url) VALUES ('T1105', 'Ingress Tool Transfer', 'Command and Control', 'https://attack.mitre.org/techniques/T1105/');
INSERT OR IGNORE INTO techniques (id, name, tactic, url) VALUES ('T1572', 'Protocol Tunneling', 'Command and Control', 'https://attack.mitre.org/techniques/T1572/');
INSERT OR IGNORE INTO techniques (id, name, tactic, url) VALUES ('T1041', 'Exfiltration Over C2 Channel', 'Exfiltration', 'https://attack.mitre.org/techniques/T1041/');
INSERT OR IGNORE INTO techniques (id, name, tactic, url) VALUES ('T1567', 'Exfiltration Over Web Service', 'Exfiltration', 'https://attack.mitre.org/techniques/T1567/');
INSERT OR IGNORE INTO techniques (id, name, tactic, url) VALUES ('T1029', 'Scheduled Transfer', 'Exfiltration', 'https://attack.mitre.org/techniques/T1029/');
INSERT OR IGNORE INTO techniques (id, name, tactic, url) VALUES ('T1486', 'Data Encrypted for Impact', 'Impact', 'https://attack.mitre.org/techniques/T1486/');
INSERT OR IGNORE INTO techniques (id, name, tactic, url) VALUES ('T1490', 'Inhibit System Recovery', 'Impact', 'https://attack.mitre.org/techniques/T1490/');
INSERT OR IGNORE INTO techniques (id, name, tactic, url) VALUES ('T1489', 'Service Stop', 'Impact', 'https://attack.mitre.org/techniques/T1489/');
